/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/cafe-3d-model_6.gltf 
*/

import React from 'react';
import {useGLTF} from '@react-three/drei';
import {Select} from '@react-three/postprocessing';
export function Coffeebara(props) {
    const {nodes, materials} = useGLTF('/coffeebara.gltf');
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.building.geometry} material={materials.building} position={[-3.213, 2.391, -2.322]} />
            <Select enabled={true}>
                <mesh
                    geometry={nodes.capy.geometry}
                    material={materials.capy}
                    position={[2.554, 5.404, -1.905]}
                    rotation={[Math.PI / 2, 0, Math.PI / 4]}
                    scale={1.325}
                />
            </Select>
            <mesh
                geometry={nodes['coffeebara-logo-right'].geometry}
                material={materials['coffeebara-logo-right']}
                position={[0.327, 3.811, -3.421]}
                rotation={[Math.PI / 2, 0, Math.PI]}
            />
            <mesh
                geometry={nodes['coffeebara-logo-left'].geometry}
                material={materials['coffeebara-logo-left']}
                position={[3.415, 3.818, 3.349]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            />
            {/* SELECT ENABLES OUTLINE ON THIS SPECIFIC MESH */}
            <Select enabled={true}>
                <mesh geometry={nodes.menu.geometry} material={materials.menu} position={[-3.213, 2.163, -2.322]} />
            </Select>

            <mesh geometry={nodes.menu.geometry} material={materials.menu} position={[-3.213, 2.163, -2.322]} />
            <Select enabled={true}>
                <mesh geometry={nodes.table.geometry} material={materials.table} position={[-3.213, 2.391, -2.322]} />
                <mesh geometry={nodes.sits.geometry} material={materials.sits} position={[-3.213, 2.391, -2.322]} />
            </Select>

            <mesh geometry={nodes['dog-bowl'].geometry} material={materials['dog-bowl']} position={[-3.213, 2.391, -2.322]} />
            <mesh
                geometry={nodes['windows-and-door'].geometry}
                material={materials['windows-and-door']}
                position={[-3.213, 2.391, -2.322]}
            />
            <mesh geometry={nodes.floor.geometry} material={materials['floor-baked']} position={[-3.213, 2.391, -2.322]} />
            <mesh geometry={nodes['rain-roof'].geometry} material={materials['rain-roof']} position={[-3.213, 2.391, -2.322]} />
            <mesh geometry={nodes.plants.geometry} material={materials.plants} position={[-3.213, 2.391, -2.322]} />
            <mesh geometry={nodes.exaustor.geometry} material={materials.exaustor} position={[-3.213, 2.391, -2.322]} />
        </group>
    );
}

useGLTF.preload('/coffeebara.gltf');
