/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Command: npx gltfjsx@6.5.0 public/cafe-3d-model_6.gltf 
*/
import {useGLTF, Html} from '@react-three/drei';
import {Selection, Select, EffectComposer, Outline} from '@react-three/postprocessing';
import InfoBallon from '../InfoBallon/InfoBallon';

const Coffeebara = ({ballonsController}) => {
    const outlineColour = '#04b4ff';

    const {nodes, materials} = useGLTF('/coffeebara1.gltf');
    return (
        <Selection>
            {/* 
                Within The Selection Component, everything wrapped by a Select Component will
                have the effects composer and outline applyed to it
            */}
            <group dispose={null}>
                <EffectComposer multisampling={8} autoClear={false}>
                    <Outline
                        blur={1}
                        visibleEdgeColor={outlineColour}
                        hiddenEdgeColor={outlineColour}
                        edgeStrength={20}
                        edgeThickness={20}
                        xRay={false}
                    />
                </EffectComposer>

                <mesh geometry={nodes.building.geometry} material={materials.building} position={[-3.213, 2.391, -2.322]} />
                <Select enabled={true}>
                    <mesh
                        geometry={nodes.capy.geometry}
                        material={materials.capy}
                        position={[2.554, 5.404, -1.905]}
                        rotation={[Math.PI / 2, 0, Math.PI / 4]}
                        scale={1.325}
                    />
                    {/* 
                        Html Drei adds an HTML element as a layer to the top of the canvas,
                    */}
                    <Html position={[4.5, 6.2, -0]} rotation-y={2.5} transform distanceFactor={8}>
                        <InfoBallon text="Hi there, I'm Capy" corner={'bottomRight'} />
                    </Html>
                </Select>
                <mesh
                    geometry={nodes['coffeebara-logo-right'].geometry}
                    material={materials['coffeebara-logo-right']}
                    position={[0.327, 3.811, -3.421]}
                    rotation={[Math.PI / 2, 0, Math.PI]}
                />
                <mesh
                    geometry={nodes['coffeebara-logo-left'].geometry}
                    material={materials['coffeebara-logo-left']}
                    position={[3.415, 3.818, 3.349]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                />
                <Select enabled={true}>
                    <mesh geometry={nodes.menu.geometry} material={materials.menu} position={[-3.213, 2.163, -2.322]} />
                    <Html position={[3.1, -0.2, -3.6]} rotation-y={2.5} transform distanceFactor={8}>
                        <InfoBallon text="Click To See Our Menu" corner={'topRight'} />
                    </Html>
                </Select>

                <Select enabled={true}>
                    <mesh geometry={nodes.table.geometry} material={materials.table} position={[-3.213, 2.391, -2.322]} />
                    <mesh geometry={nodes.sits.geometry} material={materials.sits} position={[-3.213, 2.391, -2.322]} />

                    <Html position={[4, 0.7, -0]} rotation-y={2.5} transform distanceFactor={8}>
                        <InfoBallon text="Click To Reserve a Table" corner={'topLeft'} />
                    </Html>
                </Select>

                <mesh geometry={nodes['dog-bowl'].geometry} material={materials['dog-bowl']} position={[-3.213, 2.391, -2.322]} />
                <mesh
                    geometry={nodes['windows-and-door'].geometry}
                    material={materials['windows-and-door']}
                    position={[-3.213, 2.391, -2.322]}
                />
                <mesh geometry={nodes.floor.geometry} material={materials['floor-baked']} position={[-3.213, 2.391, -2.322]} />
                <mesh geometry={nodes['rain-roof'].geometry} material={materials['rain-roof']} position={[-3.213, 2.391, -2.322]} />
                <mesh geometry={nodes.plants.geometry} material={materials.plants} position={[-3.213, 2.391, -2.322]} />
                <mesh geometry={nodes.exaustor.geometry} material={materials.exaustor} position={[-3.213, 2.391, -2.322]} />
            </group>
        </Selection>
    );
};

useGLTF.preload('/coffeebara1.gltf');
export default Coffeebara;
